### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Factory' not found in C:\Users\Refractxd\Documents\Coding\XAMPP\htdocs\firebase\index.php:7

### ISSUE THREAD

**Issue by TechStephen** [jeromegamez/firebase-php-examples#130]
PHP 7.4.10
Composer version 1.10.13

Need help!

**Comment by jeromegamez** [comment]
Please provide more information - "Class not found" is a hint that autoloading is not working correctly, a `composer install` or `composer dump-autoload` could help in that case.

**Comment by jeromegamez** [comment]
Either

```php
use Firebase\Factory;

$factory = (new Factory)->withServiceAccount();
```

or

```
Use Firebase;

$factory = (new Firebase\Factory)->withServiceAccount();
```

**Comment by jeromegamez** [comment]
Closing because not related to the SDK or this repository.

Please consider using StackOverflow or Google for general PHP questions - you can also join the Discord at https://discord.gg/nbgVfty if you have questions about the SDK.😊
