### ISSUE TITLE
I want to use social login with Firebase.

### ISSUE THREAD

**Issue by neo28edu** [jeromegamez/firebase-php-examples#275]
Thank you for creating this library. I am very honored. I am very happy to be able to learn from what you have developed. Here's a question. Is it possible to do Microsoft Login with Firebase Authentication? Sorry for the question, but I would like to know the solution. 

from Japan.

**Comment by jeromegamez** [comment]
Hey there 👋 

It is theoretically possible to do Microsoft Login authentication with the SDK (see https://firebase-php.readthedocs.io/en/stable/authentication.html#sign-in-with-idp-credentials), but I would recommend implementing the authentication part in the client (https://firebase.google.com/docs/auth/web/microsoft-oauth) and then only verifying the credentials on the backend (https://firebase-php.readthedocs.io/en/stable/authentication.html#verify-a-firebase-id-token)

**Comment by neo28edu** [comment]
thank you for your reply.
If you implement single tenant login in Azure Active Directory, you will get an error. In that case, what should I do? If you know, please let me know.

**Comment by jeromegamez** [comment]
Unfortunately I can't help with that, I have only implemented the OAuth flow on the backend as documented in the official Firebase docs, but I haven't used it myself :/
